### ISSUE TITLE
load more than 12 images

### ISSUE THREAD

**Issue by petrpscolka** [jsanahuja/InstagramFeed#1]
Hi, great library!
just one small issue is missing .. to call the "load more" function, to get more than 12 results :)
.. but yes, I know, this JSON is not part of the pre-rendered HTML. 
Any idea, how to do it?
Thank you

**Comment by jsanahuja** [comment]
Hey, thank you :)

As long as we are loading the items from the instagram page, 12 is the maximum. To load more Instagram uses a private API which is not CORS accessible
