### ISSUE TITLE
Enhancment proposal: reducing requests with some caching

### ISSUE THREAD

**Issue by typoman76** [jsanahuja/InstagramFeed#10]
Hey Thanks for that! It works perfectly. Had trouble with the api and looked for a solution to get some pics on a homepage. 
To reduce requests on the instagram website a simple caching solution would be helpful (optional). I.e. saving the result in a file and have a time interval for refreshing that file. 

Best regards, Roland

**Comment by jsanahuja** [comment]
That is not an option because this library is a client-side implementation. Also, if that would be possible, you could only save the very first request, the images would have to be requested either way.

Thank you :)
