### ISSUE TITLE
ReferenceError: InstagramFeed is not defined

### ISSUE THREAD

**Issue by vamsi3001** [jsanahuja/InstagramFeed#11]
ReferenceError: InstagramFeed is not defined
<anonymous> https://vamsithota.me/photography2/:93
<anonymous> https://vamsithota.me/photography2/:105

Here's the code I have inserted in <head> tag.
`<script src="https://cdn.jsdelivr.net/gh/jsanahuja/InstagramFeed/dist/InstagramFeed.min.js"></script>
<script>
    (function(){
        new InstagramFeed({
            'username': 'instagram',
            'container': document.getElementById("instagram-feed1"),
            'display_profile': true,
            'display_biography': true,
            'display_gallery': true,
            'callback': null,
            'styling': true,
            'items': 8,
            'items_per_row': 4,
            'margin': 1 
        });
    })();
</script>`

Here's the code I have used in <body> tag.
`<div id="instagram-feed1"></div>`

The Feed is not loading and throwing this error
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13076901/72693165-a8e41400-3b55-11ea-8a97-09e34914d6e7.png">

How do I fix this issue?

**Comment by jsanahuja** [comment]
This is the very first error you get:

`GET https://vamsithota.me/photography2/assets/js/instagramfeed.js/ net::ERR_ABORTED 404`

Also, your div `<div id="instagram-feed1"></div>` should be before the js code.

**Comment by vamsi3001** [comment]
he Feed is not loading and throwing this error when using Full Version. Which you mentioned about in the above comment. 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13076901/72693621-8b17ae80-3b57-11ea-9f03-634042a4ed45.png">

**Comment by vamsi3001** [comment]
It worked fine when added js code after the div.

It did messedup my Footer, it pushed to right side. How do I fix it?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/13076901/72693712-11cc8b80-3b58-11ea-9f17-35b3100d9cd1.png">

**Comment by jsanahuja** [comment]
`#site-main{overflow:hidden;}`
