### ISSUE TITLE
Multiple hashtags

### ISSUE THREAD

**Issue by miasalazar** [jsanahuja/InstagramFeed#12]
Hello, your library is pretty useful!
I have a question, is there any way to use multiple hashtags instead of just one?
Thank you

**Comment by jsanahuja** [comment]
Hello, there is no way to use multiple tags. An approach to that would be something like this:
```javascript
(function() {
    var tags = ['coding', 'coffee'],
        counter = 0,
        data = [];
    
    // Instances data handler
    function handler(d) {
        // Merge all images into an array
        if (typeof d.edge_hashtag_to_media.edges !== 'undefined')
            data = data.concat(d.edge_hashtag_to_media.edges);

        if (++counter == tags.length) {
            // all loaded, maybe display here?
            console.log(data);
        }
    }

    // One instance for each tag
    for (var i = 0; i < tags.length; i++) {
        new InstagramFeed({
            tag: tags[i],
            get_data: true,
            callback: handler
        });
    }
})();

```
I don't see this as something likely to be added to the library but maybe, a good enhacement would be to be able to use the `InstagramFeed.display` function statically. That would make the code above extremely easy to display through the library.

Thank you

**Comment by miasalazar** [comment]
Hi, pretty useful!
Thank you very much
