### ISSUE TITLE
Video in feed kills script

### ISSUE THREAD

**Issue by qjhammer** [jsanahuja/InstagramFeed#16]
Accounts which upload a video or have videos tend to stop or kills the script. Not loading. Even tried on the new version with changing only username in demo. Please help with this.

**Comment by jsanahuja** [comment]
I have tested with an account that the lastest 12 posts are videos and haven't found any issue. Can you please provide code examples and a screenshot?

**Comment by jsanahuja** [comment]
More info in https://github.com/jsanahuja/jquery.instagramFeed/issues/57

**Comment by jsanahuja** [comment]
Closing as fixed in 1.3.4
