### ISSUE TITLE
Custom URLs

### ISSUE THREAD

**Issue by zlipa** [jsanahuja/InstagramFeed#17]
Would it be possible to assign custom (individual) URLs to posts?

**Comment by jsanahuja** [comment]
Please elaborate your feature request. What do you mean? How should it work? What would it show?

**Comment by zlipa** [comment]
I'm trying to build a "link tree" (e.g. https://linkin.bio/sohohouse) with your code, so was wondering wether it is possible to assign unique URL's to posts.

**Comment by jsanahuja** [comment]
It is not possible and I don't think it is a general purpose feature. The only option is using the `get_data` param (See example 7 https://www.sowecms.com/demos/InstagramFeed) to get the JSON and build your custom feed. Althought, there is no way to get the data of a single post with this library.

**Comment by zlipa** [comment]
Understood, thanks. Another question, why is "items" limited to 12 on users?

**Comment by jsanahuja** [comment]
We are fetching the data from the Instagram page which displays only 12. To load more Instagram uses a private API which is not CORS accessible.
