### ISSUE TITLE
Noob ! Alert

### ISSUE THREAD

**Issue by musky603** [jsanahuja/InstagramFeed#19]
Do we need node.js for to fetch gallery?

**Comment by jsanahuja** [comment]
I am sorry but we do not offer technical support. See the examples in our documentation or index.html

**Comment by musky603** [comment]
Ok fine Thanks for the reply so Its like a trade secret 😂👍🏻 by the way 90% done by following documentation now 10% I have to research by my own

**Comment by jsanahuja** [comment]
It is not like a trade secret, the index.html provides examples of all the possibilities. You just have to check it out to get the library working. 
When you open an issue asking which file you need to modify I understand I am going to have to explain everything from scratch and considering this is a free open source library, I won't be doing that.
If you have questions about the library, feel free to ask. If you need JS support I am sorry but this is not the place

**Comment by musky603** [comment]
Oh so sorry for to feel that wrong but I just want some hint which you actually give so thanks a lot you save my day I was confused between pre tag with codes tag and actual js codes thats why I ask deep noob question from middle of no-where.
By the way Thank you so much here is test result - https://cutt.ly/instaaf
