### ISSUE TITLE
InstagramFeed: Request error. No data retrieved

### ISSUE THREAD

**Issue by yavisht** [jsanahuja/InstagramFeed#2]
Cant get feed anymore. Looks like its being blocked. Any idea whats going on?

<img width="569" alt="Screen Shot 2019-12-08 at 7 44 11 pm" src="https://user-images.githubusercontent.com/6112201/70386939-206d4200-19f3-11ea-9c6d-4ac8907f2a78.png">

**Comment by jsanahuja** [comment]
This is caused by a kind of network soft ban from Instagram. You may have done a lot of requests.
 It does not affect your website, only you.

See https://github.com/jsanahuja/jquery.instagramFeed/issues/25

**Comment by yavisht** [comment]
Thanks @jsanahuja for clarifying. I was developing a website which had BrowserSync for dev and the insta feed is in the footer so that's why I got blocked, although the tag api call is still open for me ;)
