### ISSUE TITLE
Exclude movies from feed?

### ISSUE THREAD

**Issue by Nikodemsky** [jsanahuja/InstagramFeed#21]
Right now InstagramFeed fetches all feed including movies from profiles, the problem is that movies are imported as black images with hrefs, which looks... weird.

Example:
![feed](https://user-images.githubusercontent.com/14090596/78831296-acb36400-79e9-11ea-8345-4043eab0d501.jpg)

Any way to exclude videos?

**Comment by jsanahuja** [comment]
Please provide the instagram account to test

**Comment by Nikodemsky** [comment]
https://www.instagram.com/arturpiniewski/

**Comment by jsanahuja** [comment]
The first two videos are shown as black images, exactly as they show on Instagram. The 8th item is also a video but shows properly. I don't consider this is an issue but might consider implement/accept a pull request implementing an option to exclude videos.

**Comment by musky603** [comment]
> https://www.instagram.com/arturpiniewski/

if it is your insta account so You can reupload that videos and change the thumbnail before tapping publish button
