### ISSUE TITLE
Possible to get comments?

### ISSUE THREAD

**Issue by PRF-IPA** [jsanahuja/InstagramFeed#24]
Not an actual issue, more of a question, would it be possible to get comments in the response? Also, what are the limits of this? How many requests before getting blocked?

**Comment by jsanahuja** [comment]
There is no way to get comments. For that we would have to make an other request for each image which, related to your second question, would block your network sooner. I don't know what are the Instagram restrictions but I have never been banned without trying to. The number of requests you can do before getting blocked are the same you would be able to do viewing directly your instagram page without log in.

**Comment by PRF-IPA** [comment]
@jsanahuja, that is understandable. Is this ok to use in production? I mean I hit the limits while developing the app, not sure how may requests I've made but was not in the hundreds, maybe 10-30?

**Comment by jsanahuja** [comment]
There is a lot of websites using it on production without issues. I dont think the limit is about how many requests but how often you make them
