### ISSUE TITLE
Started getting `TypeError: undefined is not an object (evaluating 'a[1].split')` for specific username

### ISSUE THREAD

**Issue by dhruveonmars** [jsanahuja/InstagramFeed#26]
I have tested, and other usernames and the demo website work, however when I use this with the username, 'blacklinesdrinks' (https://www.instagram.com/blacklinesdrinks/), I get the error `TypeError: undefined is not an object (evaluating 'a[1].split')` in the console.

I'm not sure what the issue could be, as this username was working at one point, and it doesn't appear to be a network ban as the demo website and other usernames still appear to be working.

Any help in getting this resolved would be greatly appreciated

**Comment by jsanahuja** [comment]
That is because the view of that profile is age restricted. You have to authenticate to see it so the plugin is not able to fetch the data.

**Comment by dhruveonmars** [comment]
Aah got it. I didn't even know they added an age restriction to the profile. I guess the only way to get a feed now would be with the new API?

**Comment by jsanahuja** [comment]
Probably yes. Maybe we can do the same Instagram does to load the data of age restricted profiles but might be not CORS accessible

**Comment by dhruveonmars** [comment]
I think it would be good to have a success/failure response in the callback or somewhere for when something like this happens, as I imagine others could use this with specific profiles, and not knowing if a profile changes to become private/age restricted/etc. And I imagine there could be other reasons too as to why it might fail to load an account feed

**Comment by jsanahuja** [comment]
I did add it in https://github.com/jsanahuja/InstagramFeed/commit/383eccc2a0dbe4316278a50a84a46994a153d8b5
