### ISSUE TITLE
Code not working, what am I missing?

### ISSUE THREAD

**Issue by alexndr-n** [jsanahuja/InstagramFeed#27]
Hello! First I just wanted to say this library is genious. However I'm not currently able to execute it.
I have this code

       
    const insta = document.createElement('div')
        insta.className = "instagram_feed box"
        insta.id = "instagram-feed-demo"
        insta.textContent = "Instagram pics go here"
        boxes.appendChild(insta)

        new InstagramFeed({
            username: 'myusername',
            container: "#instagram-feed-demo",
            display_profile: true,
            items: 10,
        });`

The div is displayed with the intended text but nothing else. What am I missing? Also no error on the console.

**Comment by jsanahuja** [comment]
You're using `InstagramFeed` with the syntax of `jquery.instagramFeed`. Should be

```const insta = document.createElement('div')
    insta.className = "instagram_feed box"
    insta.id = "instagram-feed-demo"
    insta.textContent = "Instagram pics go here"
    boxes.appendChild(insta)

    new InstagramFeed({
        username: 'myusername',
        container: insta,
        display_profile: true,
        items: 10,
    });

**Comment by alexndr-n** [comment]
Thanks! It works just fine. Nice work!
