### ISSUE TITLE
Images not displayed due to security policy

### ISSUE THREAD

**Issue by sophiejarlier** [jsanahuja/InstagramFeed#29]
Hi,
Thanks a lot for this great Instagram Feed solution. I have a problem with displaying Instagram images. I had to trust following url to display images:
https://scontent-cdt1-1.cdninstagram.com/v/
https://scontent-cdg2-1.cdninstagram.com/v/
How to know all urls I should accept as trusted sources? How to know which url will be used for next images to display?

Also is it possible to filter the Instagram images with hashtag?

Thanks

**Comment by jsanahuja** [comment]
I do not know which URLs Instagram uses but seeing the ones you provided I would use a wildcard `*.cdninstagram.com`

You can display the latests images of a tag but can not filter by tag over an user based feed

**Comment by sophiejarlier** [comment]
Thanks a lot! It seems to work fine with this .cdninstagram.com! For the tag pity:-( Thanks a lot for your feedback
