### ISSUE TITLE
Images not showing via username

### ISSUE THREAD

**Issue by thimfy** [jsanahuja/InstagramFeed#31]
Images not showing via username.
even your demos not showing images from username and only tag images showing.

Instagram Feed: It looks like YOUR network has been temporary banned because of too many requests. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25

ERROR in your demos
Instagram Feed: It looks like YOUR network has been temporary banned because of too many requests. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25 InstagramFeed.min.js:1:1902

**Comment by jsanahuja** [comment]
What is the purpose of this issue? I think the error is self-explaining.
