### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by nanytissot** [jsanahuja/InstagramFeed#36]
Hi, is it possible to change the items and items per row if its mobile?

**Comment by jsanahuja** [comment]
There is no such thing for now. This has been asked in the [jquery version of this plugin](https://github.com/jsanahuja/jquery.instagramFeed):
- https://github.com/jsanahuja/jquery.instagramFeed/issues/66
- https://github.com/jsanahuja/jquery.instagramFeed/issues/4

There you can find 2 workarounds
