### ISSUE TITLE
Question - can I also query images galleries ?

### ISSUE THREAD

**Issue by mylastore** [jsanahuja/InstagramFeed#37]
This is awesome by the way!!! 
Many thanks for the hard work ;)

Can this also get Instagram carousel images?

For example on img click send another request to see all the images on that gallery/carousel ? 

I had this working and on the new API  everything stopped working. :(

**Comment by jsanahuja** [comment]
Thanks :)

For now the only way to get all the images of a multipost is using the `callback`. There you have all the data in the `edge_sidecar_to_children` property of each multipost.

**Comment by mylastore** [comment]
> Thanks :)
> 
> For now the only way to get all the images of a multipost is using the `callback`. There you have all the data in the `edge_sidecar_to_children` property of each multipost.

Nice ;) I will figure out how to get all the images and carousel from this response data, again thank you.

**Comment by mylastore** [comment]
I figure out how to get the first 14 images, is it possible to get the next page of images?

**Comment by jsanahuja** [comment]
What do you mean?
