### ISSUE TITLE
npm install not found

### ISSUE THREAD

**Issue by Natetronn** [jsanahuja/InstagramFeed#38]
I tried the following but, I get the 404 error:

`npm install @jsanahuja/instagramfeed@1.4.0`

https://github.com/jsanahuja/InstagramFeed/packages/120475

```
❯ npm install @jsanahuja/instagramfeed@1.4.0
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@jsanahuja%2finstagramfeed - Not found
npm ERR! 404 
npm ERR! 404  '@jsanahuja/instagramfeed@1.4.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2020-09-03T17_09_50_891Z-debug.log
```
Is there an updated install method now that npm is part of Github, perhaps?

**Comment by Natetronn** [comment]
Okay, this seemed to work:

`npm install -S https://github.com/jsanahuja/InstagramFeed`

**Comment by jsanahuja** [comment]
When you want to install a package from the github registry you have to configure it:
```
npm config set registry https://npm.pkg.github.com/
npm install @jsanahuja/instagramfeed@1.4.0
```

After that you might want to configure back the default npm registry:
```
npm config set registry https://registry.npmjs.org/
```

Or simply install it from the default npm registry:
```
npm install jsanahuja/InstagramFeed
```

More info in #8

**Comment by Natetronn** [comment]
Thanks for the reply!

I just found this other thread in the closed section and came back to update, as it wasn't finding the file when all said and done:

https://github.com/jsanahuja/InstagramFeed/issues/8#issuecomment-582005226

So, this install worked for me:

`npm install jsanahuja/InstagramFeed`

And I import like so:

`import InstagramFeed from '@jsanahuja/instagramfeed';`
