### ISSUE TITLE
Hashtags feed not displaying? What to do

### ISSUE THREAD

**Issue by musky603** [jsanahuja/InstagramFeed#42]
I was browsing this website https://www.sowecms.com/demos/InstagramFeed/ and click on example 4 for to test hashtag feeds but unfortunately it fail to display on any mobile browser. 
I don't know whether its happen to only my network and devices but seems to be very awkward 
I will try to discover the real error from p.c when I get time.

**Comment by jsanahuja** [comment]
The problem is on Instagram. They are returning an error 501 for any (I believe) tag URL: https://www.instagram.com/explore/tags/paradise/

FYI: https://www.reddit.com/r/Instagram/comments/isvpu9/explore_page_not_working_on_browser/

**Comment by musky603** [comment]
Thanks for the research and solutions, finally it displaying the feeds today
