### ISSUE TITLE
FireFox CORS Error

### ISSUE THREAD

**Issue by dennismetz** [jsanahuja/InstagramFeed#43]
I'm running into the error (Firefox only) "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at..."

I'm using a Plesk Server with nginx as reverse proxy and everything i tried isn't working...

Any Ideas?
Using jsonp instead of xhr?

**Comment by jsanahuja** [comment]
I just tried in firefox and it is working for me
