### ISSUE TITLE
InstagramFeed stoped working

### ISSUE THREAD

**Issue by urza** [jsanahuja/InstagramFeed#50]
Hello good people, InstagramFeed stoped working on my site.

This is the error in console:

InstagramFeed: Unable to fetch the given user/tag. Instagram responded with the status code: No Reason Phrase 5

I am using curren version from master branch (minified).

This is my script:

```
<script>
    (function () {
        new InstagramFeed({
            'username': 'yogenabrno',
            'container': document.getElementById("insta1"),
            'display_profile': false,
            'display_biography': false,
            'display_gallery': true,
            'callback': null,
            'styling': true,
            'items': 4,
            'items_per_row': 4,
            'margin': 1,
            'image_size': 640
        });
    })();
</script>

```

**Comment by edknittel** [comment]
I too can confirm that the script has stopped working for me as well. Has anything changed on Instagram's side?

**Comment by pabrul** [comment]
I also have this same problem, the console gave me this error
![image](https://user-images.githubusercontent.com/55573363/104344003-5ecd0e80-54db-11eb-964f-cfc3c502b0bd.png)

**Comment by pabrul** [comment]
This error is happening to a lot of people, but the admin is closing the problems before it is solved

**Comment by MattTrovao** [comment]
I update the jquery version of the plugin, and get this error  `(index):708 Uncaught TypeError: $.instagramFeed is not a function` , but before i was getting the same error.

**Comment by edknittel** [comment]
It appears that the plugin still works on iPhone. This is likely due to Instagram restricting access to public accounts on computers and tablets

**Comment by artshostak** [comment]
Stopped working for me to across all projects, subscribing for updates.

**Comment by jsanahuja** [comment]
This should be fixed soon with #49. If anyone wants to send a PR implementing it, please coment there

> I update the jquery version of the plugin, and get this error `(index):708 Uncaught TypeError: $.instagramFeed is not a function` , but before i was getting the same error.

This is not the [jQuery repository](https://github.com/jsanahuja/jquery.instagramFeed)

**Comment by jhvanderschee** [comment]
This tool is not working in (my) Firefox. Firefox blocks almost all functionality because of its native anti-tracking rules and so do all ad-blockers. I hope and expect this 'blocking' to increase over time. Apart from the fact that this tool (already) does not work for a substantial part of the internet, it also tricks its visitors into the mass surveillance system Facebook has created. Finally, the image retrieval from Facebook slows websites down and makes them violate the law in the EU. I think you should warn people for that... What do you think?

**Comment by artshostak** [comment]
Been a couple of weeks here, just wondering if we are any closer to an update? I see that the jQuery version rolled one out already and really don't want to switchover but considering it.

**Comment by RosalieWessels** [comment]
I have the same problem here. Does anybody know when this will be fixed?

**Comment by krausenspb** [comment]
It is new limit for non-auth users.

```
“If you are not logged in Instagram, you may only see a certain amount of posts on public profiles before being asked to login”, they said. “This is to help people view photos in Instagram and understand how to have the best experience on the platform, be part of the community, connecting and interacting with people and the things they love”.

This is a different issue. Since at least November 2019, viewing of public post is limited when a person not logged scrolls the page a bit — see this report from The Next Web. What is new is a much more restrict limit, which doesn’t allow unlogged people to see even one photo or video.
```

**Comment by Jalinco1** [comment]
Damit, I got blocked too, I wonder how long...
I did even try other IP, still blocked...

**Comment by jsanahuja** [comment]
This is usually because you've been banned. Should happen less times with the [2.0.1 release](https://github.com/jsanahuja/InstagramFeed/releases/tag/2.0.1) as of we have implemented client-side caching in #54.

If you are not banned but still getting unexpected errors, please provide Instagram's HTTP response (browser's network tab) and console stack trace using the not minified version in a new issue.

Thank you

**Comment by jsanahuja** [comment]
@pabrul
> This error is happening to a lot of people, but the admin is closing the problems before it is solved

We do not close anything unless it is duplicated or without enough info. Also, as long as this is open source, you can fix the problem yourself and send a PR (following [CONTRIBUTING.md](https://github.com/jsanahuja/InstagramFeed/blob/master/CONTRIBUTING.md)) if you want.

**Comment by jsanahuja** [comment]
@pabrul
> I also have this same problem, the console gave me this error
> ![image](https://user-images.githubusercontent.com/55573363/104344003-5ecd0e80-54db-11eb-964f-cfc3c502b0bd.png)

There is nothing we can do with this.
