### ISSUE TITLE
CORS policy error and temporary banned

### ISSUE THREAD

**Issue by robertoboldi** [jsanahuja/InstagramFeed#51]
Dear all, 
I have some issues on this really useful library.
first of all I got the CORS Policy error:

Access to XMLHttpRequest at 'https://www.instagram.com/batman/' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

when I retried i got this other error: 
InstagramFeed: It looks like YOUR network has been temporary banned because of too many requests. See https://github.com/jsanahuja/jquery.instagramFeed/issues/25

Following the link https://github.com/jsanahuja/jquery.instagramFeed/issues/25 i found the solution to other issues.

I have simply tested the application putting the following in my html:
<script src="/instagramfeed.min.js"></script>
<script>
    (function(){
        new InstagramFeed({
            'username': 'batman',
            'container': document.getElementById("instagram"),
            'display_profile': false,
            'display_biography': false,
            'display_gallery': true,
            'display_captions': false,
            'callback': null,
            'styling': true,
            'items': 8,
            'items_per_row': 4,
            'margin': 1 
        });
    })();
</script>

is some error of my code? can I do something to solve this?
any suggestions?

Thank you very much
Cheers
R

**Comment by jsanahuja** [comment]
This is usually because you've been banned. Should happen less times with the [2.0.1 release](https://github.com/jsanahuja/InstagramFeed/releases/tag/2.0.1) as of we have implemented client-side caching in #54.

**Comment by robertoboldi** [comment]
thank you very much, I've updated my file with the latest release. 
Is still valid the usage of the following for the CORS policies? I keep it in my code and go on

'https://images' + ~~(Math.random() * 3333) + '-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/'

thanks again
Cheers
R
