### ISSUE TITLE
CORS policy workaround

### ISSUE THREAD

**Issue by piotrmerton** [jsanahuja/InstagramFeed#55]
For anyone encountering CORS policy errors, try using this as a host:

`'host': "https://images" + ~~(Math.random() * 3333) + "-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/"`

Solution provided by @colinchadwick here https://github.com/jsanahuja/jquery.instagramFeed/issues/103#issuecomment-788260968

**Comment by QuranIslam** [comment]
Sorry but I think it is not working
![image](https://user-images.githubusercontent.com/47284416/109653695-fa890b80-7b69-11eb-8374-ad353963997b.png)

**Comment by jsanahuja** [comment]
Implemented in [3.0.1](https://github.com/jsanahuja/InstagramFeed/releases/tag/3.0.1). Highly recommended to set the `host` parameter as follow:
`'host': "https://images" + ~~(Math.random() * 3333) + "-focus-opensocial.googleusercontent.com/gadgets/proxy?container=none&url=https://www.instagram.com/"` this parameter

**Comment by jsanahuja** [comment]
> Sorry but I think it is not working
> ![image](https://user-images.githubusercontent.com/47284416/109653695-fa890b80-7b69-11eb-8374-ad353963997b.png)

This is because you are doing the requests without a server (referer header). You should try using a web server as it was stated here: https://github.com/jsanahuja/jquery.instagramFeed/issues/117

**Comment by RomainDW** [comment]
The fix creates a new problem for me: `Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.instagram.com/p/CL7rMUKDOaR/ with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

Images don't display and have a URL like this instead: [https://lookaside.instagram.com/seo/google_widget/crawler/?media_id=2520798378721076881](https://lookaside.instagram.com/seo/google_widget/crawler/?media_id=2520798378721076881)

![image](https://user-images.githubusercontent.com/35602101/109792969-5f00a500-7c14-11eb-9341-fc94aa0af082.png)

**Comment by jsanahuja** [comment]
> lookaside.instagram.com/seo/google_widget/crawler/?

Please open a new issue with information to reproduce it
