### ISSUE TITLE
InstagramFeed is not defined

### ISSUE THREAD

**Issue by toccamonium-fe** [jsanahuja/InstagramFeed#58]
Hi, thanks for cool plugin. 

I integrated it, but I get this error, any idea what went wrong?

![grafik](https://user-images.githubusercontent.com/55410878/112140784-bfac4d80-8bd4-11eb-9ddb-6fca16ab5efd.png)

**Comment by jsanahuja** [comment]
Instead of guessing, show your code and we will tell you what is wrong

**Comment by toccamonium-fe** [comment]
sure

```
<script src="/js/instagram.js"></script>
<script>
    (function(){
        new InstagramFeed({
            'username': 'github',
            'container': document.getElementById("instagram-feed2"),
            'display_profile': false,
            'display_biography': false,
            'display_gallery': true,
            'display_captions': false,
            'callback': null,
            'styling': true,
            'items': 8,
            'items_per_row': 5,
            'margin': 1 
        });
    })();
</script>
```

**Comment by jsanahuja** [comment]
Should work unless `/js/instagram.js` does not exist. Also you should use the `.min.js` version if you aren't

**Comment by toccamonium-fe** [comment]
Checked it in the the dev tool, JS is actually there. Anyway, I'm going to test it somewhere else for double check and let you know.

**Comment by jsanahuja** [comment]
Im closing this as this support request is more into web fundamentals than this library itself
