### ISSUE TITLE
Publish to npmjs and allow for import access

### ISSUE THREAD

**Issue by JamesFreeman** [jsanahuja/InstagramFeed#8]
Hi there, this looks like an amazing project.  

I'm trying to install this into my project via `yarn` but it doesn't look like you've published it to a npmjs site and created a tagged release. Would it be possible to do this?

Also, would it be possible to give us the ability to import the project instead of having have a hardcoded .js in the header?

This would enable a developer to do something like this:
```
<script>
import InstagramFeed from 'jsanahuja/InstagramFeed';

export default{
	mount(){
		InstagramFeed({
			'username': 'instagram',
			'container': document.getElementById("instagram-feed1"),
			'display_profile': true,
			'display_biography': true,
			'display_gallery': true,
			'callback': null,
			'styling': true,
			'items': 8,
			'items_per_row': 4,
			'margin': 1 
		});
	}
}
</script>
```

**Comment by dhruveonmars** [comment]
Any idea if this has been done, or if it's in progress, or not happening?

I'd like to add it to a Shopify Custom Theme Section, so that it's not unnecessarily loaded on all pages.

**Comment by jsanahuja** [comment]
Added AMD support, please test it.

**Comment by jsanahuja** [comment]
You should now be able to install it using:

`npm install jsanahuja/instagramfeed`

Thank you both

**Comment by dhruveonmars** [comment]
Hey @jsanahuja Thanks for adding it, however after installing, and adding `import { InstagramFeed } from "@jsanahuja/instagramfeed";`, I get _Module not found: Error: Can't resolve '@jsanahuja/instagramfeed'_

**Comment by jsanahuja** [comment]
What is your environment? Vanilla JS, webpack, node?
A repository example would be helpful

Thanks!

**Comment by jsanahuja** [comment]
I believe it should work now. I tested with `webpack`:
```javascript
import InstagramFeed from '@jsanahuja/instagramfeed';

console.log(InstagramFeed);

const root = document.createElement("div")
root.id = 'instagram-feed'
document.body.appendChild(root)

new InstagramFeed({
    'username': 'instagram',
    'container': document.getElementById("instagram-feed"),
    'display_profile': true,
    'display_biography': true,
    'display_gallery': true,
    'callback': null,
    'styling': true,
    'items': 8,
    'items_per_row': 4,
    'margin': 1
});
```
Please try with the new @1.2.3 release
Thank you!

**Comment by robsonsobral** [comment]
HI! Thank you for adding, but it looks like something is broken. I can't find the package on NPM.

**Comment by ymongo** [comment]
From https://yarnpkg.com/package/instafeed i got it workin gon nuxt. 

Please update your doc: yarn add instafeed 

then 

`import InstagramFeed from 'instafeed'`

**Comment by jsanahuja** [comment]
> From https://yarnpkg.com/package/instafeed i got it workin gon nuxt.
> 
> Please update your doc: yarn add instafeed
> 
> then
> 
> `import InstagramFeed from 'instafeed'`

That is not related to this repository

> HI! Thank you for adding, but it looks like something is broken. I can't find the package on NPM.

For me it works using `npm install jsanahuja/InstagramFeed`

If you are trying as it shows [here](https://github.com/jsanahuja/InstagramFeed/packages/120475) then you need to configure the github registry in your NPM:

```
npm config set registry https://npm.pkg.github.com/
npm install @jsanahuja/instagramfeed@1.4.0
```
Note that you will have to configure back your registry to install packages that are not in the github registry:
```
npm config set registry https://registry.npmjs.org/
```
