### ISSUE TITLE
Post Captions

### ISSUE THREAD

**Issue by JS-Design** [jsanahuja/InstagramFeed#9]
Hey, i'm trying to find a way to get the img caption, however it doesn't look like its being pulled.
I'm have no clue how to add this myself, so im asking if its possible to do

checked, console.log( img[ i ] ); but cannot find a field which would represent the caption in any way.

node:
__typename: "GraphImage"
id: "2198312878692136426"
edge_media_to_caption: {edges: Array(1)}
shortcode: "B6B-ep_nHXq"
edge_media_to_comment: {count: 1}
comments_disabled: false
taken_at_timestamp: 1576279338
dimensions: {height: 1077, width: 1080}
display_url: "https://scontent-lht6-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/75403225_204983533864953_2689988167004388606_n.jpg?_nc_ht=scontent-lht6-1.cdninstagram.com&_nc_cat=109&_nc_ohc=oNBmJmAPIwgAX-suKkn&oh=5212027434a0b365434dd26945746737&oe=5E796872"
edge_liked_by: {count: 45}
edge_media_preview_like: {count: 45}
location: null
gating_info: null
fact_check_overall_rating: null
fact_check_information: null
media_preview: "ACop5qirDCNkXbkSchh1z6MPT0I9s1EE9SBQK5OLGYx+aF+TGc9sVVq55jiMxb/kJyV7Zqttz0IP6UCTGUVOgRVbzM7sYQepPcn0A7dyRUNAyUEviNByxxx1J7UtxbSWzbJV2kjPY8fUZFWJrCe2mWL7zn5l2/5GMYqG6klkf9+TvXj5uCPbFIS0LS6cGi8zd1Qv935f90t2PB68ZwOpFUoIHuH8uMbmPOOB09zxSea4Ty9x2Hnbk4/LpTrbzPMHk58w8Db1/wA+vamMHLxExuOVOCD2qP5feuhitVt3CuVlu5c4DcqmRklvU/5HqazaBcZPKfmR/wCy0hLyJmWW1IvBMsxwAQepB7Dn/CromtNTTEoCOB3OGH+63cex/Kueu/8AWN9aq0ErVXFkADEIdygnB6ZHrVi0u3tSzR/eYY6dPf6/5NVTRTLsOMjM24kk9c98+uaDK5OSzEn3NMrsYP8AVr/uj+QpPQmT5eh//9k="
owner: {id: "1278618971", username: "watchitallabout"}
thumbnail_src: "https://scontent-lht6-1.cdninstagram.com/v/t51.2885-15/sh0.08/e35/c1.0.1280.1280a/s640x640/75403225_204983533864953_2689988167004388606_n.jpg?_nc_ht=scontent-lht6-1.cdninstagram.com&_nc_cat=109&_nc_ohc=oNBmJmAPIwgAX-suKkn&oh=0135f466cbc674c7bf05143b2637a0a2&oe=5E755E1C"
thumbnail_resources: (5) [{…}, {…}, {…}, {…}, {…}]
is_video: false
accessibility_caption: "Image may contain: night"

**Comment by JS-Design** [comment]
Eventually i found the variable. and added it to the the markup, consider adding this in as an option

var caption = imgs[i].node.edge_media_to_caption.edges[0].node.text;

**Comment by jsanahuja** [comment]
Pending to do the same done here https://github.com/jsanahuja/jquery.instagramFeed/issues/33
